pipeline:
  name: terrafom
  identifier: terrafom
  projectIdentifier: terraformprod
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Terraform_Deploy
        identifier: Terraform_Deploy
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Terraform Init
                  identifier: terraform_init
                  spec:
                    shell: Sh
                    image: hashicorp/terraform:1.8.5
                    command: |
                      terraform version
                      terraform init
              - step:
                  type: Run
                  name: Terraform Plan
                  identifier: terraform_plan
                  spec:
                    shell: Sh
                    image: hashicorp/terraform:1.8.5
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("AWS_ACCESS_KEY_ID")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("AWS_SECRET_ACCESS_KEY")>
                      AWS_DEFAULT_REGION: us-east-1
                    command: |
                      terraform plan -out=tfplan
              - step:
                  type: Run
                  name: Terraform Apply
                  identifier: terraform_apply
                  spec:
                    shell: Sh
                    image: hashicorp/terraform:1.8.5
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("AWS_ACCESS_KEY_ID")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("AWS_SECRET_ACCESS_KEY")>
                      AWS_DEFAULT_REGION: us-east-1
                    command: |
                      terraform apply -auto-approve tfplan
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
